# Generated by Django 6.0.5 on 2026-05-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel API')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect - Owned)'), ('SCOPE_3', 'Scope 3 (Indirect - Value Chain)')], max_length=20)),
                ('raw_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analyst Review'), ('APPROVED', 'Approved for Audit'), ('FLAGGED', 'Suspicious / Error')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_source_row', models.JSONField(help_text='Store the exact incoming JSON/CSV row')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_inspector.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_inspector.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_inspector.tenant'),
        ),
    ]
